### ISSUE TITLE
Protocol for controlling LEDs

### ISSUE THREAD

**Issue by samuelcomplex** [freman/lua-sexyleds#1]
How do you control the LEDs?

There's no documentation on the type of protocol or the commands that work, would greatly appreciate if you could add this.

@freman

**Comment by freman** [comment]
Whelp, it's been about 2 years since I looked at this code... Let's take a look...

task.lua
Listens on TCP port 48879
Seems to take some strings

on
off
bn where n is number from 0 to 255 for brightness.
r,g,b where r,g,b is numbers from 0 to 255 for their respective colours.

Device responds with a K whether it understands your command or not, then closes the connection, meaning one connection per command.

Seems I might have been aiming for the simplest possible protocol possible (prolly cos I was just firing commands at it with telnet), yay me!

**Comment by samuelcomplex** [comment]
Great, thanks! Now I just have to find a way to send it commands from a windows machine :P

Tried putty, as soon as I connect I get a "K" and then it closes.

**Comment by samuelcomplex** [comment]
Same with built in telnet client. I can connect but as soon as I press a button to type a command I get "k" and is closes connection.

Tried using a file with a command in it, like on, off, 0,0,0, b0, b100 etc. Won't have it.

**Comment by samuelcomplex** [comment]
Solved that bit. But I'm thinking something is wrong because whatever I send I get "k" but nothing changes on the light. Note even on/off works. *sigh*

**Comment by freman** [comment]
If I'm not mistaken, you should be able to add setColorRGB(255,255,255) to the empty line before srv=net.createServer(net.TCP).

This should turn the leds on, "white", if it doesn't I might suggest a wiring issue.

I forget which pins '4' and '5' correspond to in Lua land

**Comment by freman** [comment]
Heh off and on don't actually do anything. Guess I wasn't finished

**Comment by samuelcomplex** [comment]
Well that certainly explains that :P I'll try setting the color and reupload. Thanks for all the help :)
